### ISSUE TITLE
Corer$criteria_plot() returning error 

### ISSUE THREAD

**Issue by max-schofield** [trophia/analyser#7]
rerunning reports today generates the error:
## Error: Unknown column 'trips'

I'm yet to see what has changed to generate this but will let you know if I find anything.

**Comment by nokome** [comment]
I'll look into it too

**Comment by nokome** [comment]
Hopefully commit 6daa089298988d93266a3bcc73cd062d430de8d5 fixes this. Closing for now, reopen if it doesn't.

**Comment by max-schofield** [comment]
Looks like this will need to be reopened, the same issue is persisting: 
unknown column trips

**Comment by nokome** [comment]
This is working for me locally so perhaps there is a change in the extracted data that is causing this. I'll download it and have a look.
